services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails db:migrate && bundle exec rake db:seed && rails server -b 0.0.0.0"
    volumes:
      - .:/yeventcms
    ports:
      - "3000:3000"